[tool.poetry]
name = "bds"
version = "0.1.0"
description = ""
authors = ["Han Xiao <xiaohan2012@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
seaborn = "^0.12.2"
ortools = "^9.5.2237"
pandas = "^1.5.3"
notebook = "^6.5.2"
ray = "^2.2.0"
pytest = "^7.2.1"
jupyter-nbextensions-configurator = "^0.6.1"
logzero = "^1.7.0"
scikit-learn = "^1.2.1"
tqdm = "^4.64.1"
galois = "^0.3.3"
cvxpy = "^1.3.0"
mlxtend = "^0.21.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
