name: Lint

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
  autoflake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: creyD/autoflake_action@v1.1
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isort/isort-action@v1
        with:
            # requirements-files: "requirements.txt"  # seems unncessary
            configuration: "--profile black --check-only --diff"
